AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  soonaverse-nft-bot

Globals:
  Function:
    Timeout: 120
    MemorySize: 2048

Resources:
  RoleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: schedule
          Properties:
            Schedule: rate(1 hour)
            Name: hourly
            Description: Triggers once an hour
            Enabled: True
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  HelloWorldFunction:
    Description: "Role Lambda Function ARN"
    Value: !GetAtt RoleFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for RoleFunction"
    Value: !GetAtt RoleFunctionRole.Arn
